unsubscribe_url:     "http://###.com"

#Social Media links

twitterUrl:          "https://twitter.com/###"
facebookUrl:         "https://www.facebook.com/###"
vimeoUrl:            "https://vimeo.com/###"
youtubeUrl:          "https://www.youtube.com/user/###"
googlePlusUrl:       "https://plus.google.com/+###"